version: '3'

services:

  db:
    build: mariadb/
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_APP_DB}
      - MYSQL_USER=${MYSQL_APP_USER}
      - MYSQL_PASSWORD=${MYSQL_APP_PASSWORD}
    volumes:
      - /data/pre-prod/db/data:/var/lib/mysql
    restart: always
    networks:
      - pre-prod

  memcached:
    image: memcached:alpine
    entrypoint:
      - memcached
      - -m
      - '256'
    restart: always
    networks:
      - pre-prod

  web:
    build: stayhome/
    environment:
      - RUNNING_ENV=pre-prod
      - MYSQL_APP_DB=${MYSQL_APP_DB}
      - MYSQL_APP_USER=${MYSQL_APP_USER}
      - MYSQL_APP_PASSWORD=${MYSQL_APP_PASSWORD}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - SYNC_USER=${SYNC_USER}
      - SYNC_PASSWORD=${SYNC_PASSWORD}
      - RECAPTCHA_PUBLIC_KEY=${RECAPTCHA_PUBLIC_KEY}
      - RECAPTCHA_PRIVATE_KEY=${RECAPTCHA_PRIVATE_KEY}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - SENTRY_DSN=${SENTRY_DSN}
      - GOOGLE_UA=${GOOGLE_UA}
      - DATADOG_ENV=pre-prod
      - DD_AGENT_HOST=datadog
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_PROFILING_API_KEY=${DD_PROFILING_API_KEY}
      - DD_PROFILING_TAGS=env:pre-prod,service:stayhome,version:1
      - DD_WEB_API_KEY=${DD_WEB_API_KEY}
      - DD_WEB_APP_KEY=${DD_WEB_APP_KEY}
      - LOCIZE_API_KEY=${LOCIZE_API_KEY}
    expose:
      - 8000
      - 9001-9050
    depends_on:
      - db
      - memcached
    restart: always
    volumes:
      - api_key:/api
      - datasets:/code/datasets
    networks:
      - pre-prod

  sync-service:
    build: sync-service/
    environment:
      - STAYHOME_API_URL=http://web:8000/api
      - SPRING_PROFILES=pre-prod
      - SENTRY_DSN=${SENTRY_DSN_SYNC}
    expose:
      - 8080
    depends_on:
      - web
    restart: always
    volumes:
      - api_key:/api
    networks:
      - pre-prod
  
  nodefetch:
    build: nodefetch/
    environment:
      - SYNC_SERVICE_BASE_URL=http://sync-service:8080/api/
    depends_on:
      - sync-service
    restart: always
    networks:
      - pre-prod

  integration-kml:
    build: integrations/kml-parser
    environment:
      - STAYHOME_SYNC_SERVICE_URL=http://sync-service:8080
      - STAYHOME_RUN_ON_START=true
      # every 6h
      - STAYHOME_INTEGRATIONS_KML_SCRAPE_CRON=* * */6 * * *
    depends_on:
      - sync-service
    restart: always
    networks:
      - pre-prod

  contribute:
    build: contribute/
    expose:
      - 80
    depends_on:
      - web
    restart: always
    networks:
      - pre-prod

  statsbot:
    build: statsbot/
    expose:
      - 3333
      - 3434
    restart: always
    networks:
      - pre-prod

  haproxy:
    build: haproxy/
    environment:
    - LETSENCRYPT_HOST=preview.stayhome.ch
    - VIRTUAL_HOST=preview.stayhome.ch
    - VIRTUAL_PORT=8000
    expose:
      - 8000
      - 8404
    depends_on:
      - web
      - contribute
      - statsbot
    restart: always
    networks:
      - pre-prod

volumes:
  api_key:
  datasets:

networks:
  pre-prod:
    external:
      name: infra_pre-prod
